# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iRayX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  
  pod 'SnapKit'
  pod 'SDWebImage'

  # Pods for iRayX

  target 'iRayXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iRayXUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
